version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./containers/app/Dockerfile
    image: atrato-app
    container_name: atrato-app
    restart: always
    ports:
      - "3000:3000"
    command: >
      node server.js
    networks:
      - local
    depends_on:
      - db

  client:
    build:
      context: .
      dockerfile: ./containers/client/Dockerfile
    image: atrato-client
    container_name: atrato-client
    restart: always
    ports:
      - "80:80"

  db:
    image: mysql:latest
    container_name: atrato-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 36Xf5Cgk6uNNctrj
      MYSQL_DATABASE: atrato
      MYSQL_USER: atrato
      MYSQL_PASSWORD: ZvX64X36
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  mysql-data: